[project]
name = "act1-7-obtencionyalmacenamiento"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "plotly>=6.5.2",
    "polars>=1.38.1",
    "requests>=2.32.5",
    "statsmodels>=0.14.6",
]
